# ▄▄▄    ▄▄▄   ▄▄▄▄▄     ▄▄▄▄▄   ▄▄▄▄▄▄   ▄▄▄      ▄▄▄▄▄ ▄▄▄    ▄▄▄  ▄▄▄▄▄▄▄
# ████▄  ███ ▄███████▄ ▄███████▄ ███▀▀██▄ ███       ███  ████▄  ███ ███▀▀▀▀▀
# ███▀██▄███ ███   ███ ███   ███ ███  ███ ███       ███  ███▀██▄███ ███
# ███  ▀████ ███▄▄▄███ ███▄▄▄███ ███  ███ ███       ███  ███  ▀████ ███  ███▀
# ███    ███  ▀█████▀   ▀█████▀  ██████▀  ████████ ▄███▄ ███    ███ ▀██████▀
#
#   ▄▄▄▄▄▄▄   ▄▄▄▄▄   ▄▄▄▄▄▄▄    ▄▄▄▄▄▄▄
# ███▀▀▀▀▀ ▄███████▄ ███▀▀███▄ ███▀▀▀▀▀
# ███      ███   ███ ███▄▄███▀ ███▄▄
# ███      ███▄▄▄███ ███▀▀██▄  ███
# ▀███████  ▀█████▀  ███  ▀███ ▀███████
# ──────────────────────────────────────────────────────────────
#
#   MacOSBundler - Creates macOS .app bundles
#
#   Creates a standalone .app that: 1. Contains the runtime m...
#
# ──────────────────────────────────────────────────────────────
# MODULE:   applications.noodlestudio.appbuilder.bundler_macos
# PURPOSE:  MacOSBundler - Creates macOS .app bundles
# LAYER:    Studio / Build System
# ──────────────────────────────────────────────────────────────
#
# KEY CLASSES:
#   MacOSBundler, is_macos(), get_system_python_path()
#
# ──────────────────────────────────────────────────────────────
# SPDX-License-Identifier: AGPL-3.0-or-later
# Subject to the Noodling Ethical Covenant (NEC)
# (C) 2026 Caitlyn Meeks
# Noodling Technologies, LLC
# https://noodlings.ai
# ──────────────────────────────────────────────────────────────

import logging
import os
import plistlib
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Any, Callable, Dict, Optional

logger = logging.getLogger(__name__)

# Info.plist template
INFO_PLIST_TEMPLATE = {
    'CFBundleDevelopmentRegion': 'en',
    'CFBundleExecutable': '',  # Filled in
    'CFBundleIconFile': 'AppIcon',
    'CFBundleIdentifier': '',  # Filled in
    'CFBundleInfoDictionaryVersion': '6.0',
    'CFBundleName': '',  # Filled in
    'CFBundlePackageType': 'APPL',
    'CFBundleShortVersionString': '',  # Filled in
    'CFBundleVersion': '1',
    'LSMinimumSystemVersion': '13.0',
    'NSHighResolutionCapable': True,
    'NSPrincipalClass': 'NSApplication',
    'NSRequiresAquaSystemAppearance': False,  # Support dark mode
}

# Launcher script template
LAUNCHER_SCRIPT = '''#!/bin/bash
# NoodleStudio Runtime Launcher
# Generated by NoodleStudio Build System

# Get the directory containing this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONTENTS_DIR="$(dirname "$SCRIPT_DIR")"
RESOURCES_DIR="$CONTENTS_DIR/Resources"

# Project and runtime paths
PROJECT_DIR="$RESOURCES_DIR/project"
RUNTIME_DIR="$RESOURCES_DIR/runtime"

# Find Python
# Priority: bundled Python > system Python 3
if [ -d "$RESOURCES_DIR/python" ]; then
    PYTHON="$RESOURCES_DIR/python/bin/python3"
elif command -v python3 &> /dev/null; then
    PYTHON="python3"
else
    osascript -e 'display alert "Python 3 Required" message "Please install Python 3 to run this application." as critical'
    exit 1
fi

# Set up environment
export PYTHONPATH="$RUNTIME_DIR:$PYTHONPATH"
export NOODLE_PROJECT_PATH="$PROJECT_DIR"

# Run the application
cd "$PROJECT_DIR"
exec "$PYTHON" -m noodlestudio.runtime "$PROJECT_DIR" --gui
'''


class MacOSBundler:
    """
    Creates macOS .app bundles.

    Usage:
        bundler = MacOSBundler(config, staging_dir)
        result = bundler.bundle(Path("~/Desktop/MyApp.app"))
    """

    def __init__(self, config: 'BuildConfig', staging_dir: Path):
        """
        Initialize bundler.

        Args:
            config: Build configuration
            staging_dir: Directory containing staged files
        """
        self.config = config
        self.staging_dir = Path(staging_dir)
        self._progress_callback: Optional[Callable[[float, str], None]] = None

    def on_progress(self, callback: Callable[[float, str], None]):
        """Register progress callback (0.0 to 1.0)."""
        self._progress_callback = callback

    def _report_progress(self, percent: float, message: str):
        """Report progress."""
        if self._progress_callback:
            self._progress_callback(percent, message)

    def bundle(self, output_path: Path) -> Dict[str, Any]:
        """
        Create the .app bundle.

        Args:
            output_path: Where to create the .app

        Returns:
            Dict with success status
        """
        output_path = Path(output_path)

        # Ensure .app extension
        if not output_path.suffix == '.app':
            output_path = output_path.with_suffix('.app')

        try:
            # Remove existing bundle if present
            if output_path.exists():
                shutil.rmtree(output_path)

            # Create bundle structure
            self._report_progress(0.0, "Creating bundle structure...")
            contents_dir = output_path / "Contents"
            macos_dir = contents_dir / "MacOS"
            resources_dir = contents_dir / "Resources"

            macos_dir.mkdir(parents=True)
            resources_dir.mkdir(parents=True)

            # Create Info.plist (0-10%)
            self._report_progress(0.1, "Creating Info.plist...")
            self._create_info_plist(contents_dir)

            # Create launcher script (10-20%)
            self._report_progress(0.2, "Creating launcher...")
            self._create_launcher(macos_dir)

            # Copy icon (20-30%)
            self._report_progress(0.3, "Processing icon...")
            self._copy_icon(resources_dir)

            # Copy runtime module (30-60%)
            self._report_progress(0.4, "Copying runtime...")
            self._copy_runtime(resources_dir)

            # Copy project files (60-90%)
            self._report_progress(0.6, "Copying project...")
            self._copy_project(resources_dir)

            # Finalize (90-100%)
            self._report_progress(0.9, "Finalizing bundle...")

            # Make launcher executable
            launcher = macos_dir / self._get_executable_name()
            launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

            self._report_progress(1.0, "Bundle created")

            return {
                'success': True,
                'output_path': output_path
            }

        except Exception as e:
            logger.exception(f"Bundle creation failed: {e}")
            return {
                'success': False,
                'errors': [str(e)]
            }

    def _get_executable_name(self) -> str:
        """Get the executable name (sanitized app name)."""
        # Remove spaces and special chars for the executable
        name = self.config.name
        name = ''.join(c for c in name if c.isalnum() or c in '-_')
        return name or 'NoodleApp'

    def _create_info_plist(self, contents_dir: Path):
        """Create Info.plist."""
        plist = INFO_PLIST_TEMPLATE.copy()

        plist['CFBundleExecutable'] = self._get_executable_name()
        plist['CFBundleIdentifier'] = self.config.identifier
        plist['CFBundleName'] = self.config.name
        plist['CFBundleShortVersionString'] = self.config.version

        plist_path = contents_dir / "Info.plist"
        with open(plist_path, 'wb') as f:
            plistlib.dump(plist, f)

        logger.info(f"Created Info.plist: {plist['CFBundleName']}")

    def _create_launcher(self, macos_dir: Path):
        """Create the launcher shell script."""
        launcher_path = macos_dir / self._get_executable_name()

        with open(launcher_path, 'w') as f:
            f.write(LAUNCHER_SCRIPT)

        logger.info(f"Created launcher: {launcher_path}")

    def _copy_icon(self, resources_dir: Path):
        """Copy and convert icon to .icns format."""
        if not self.config.icon:
            # Use default icon or skip
            logger.info("No icon specified, using default")
            return

        icon_src = self.config.project_path / self.config.icon
        if not icon_src.exists():
            logger.warning(f"Icon not found: {icon_src}")
            return

        icon_dst = resources_dir / "AppIcon.icns"

        # If already .icns, just copy
        if icon_src.suffix.lower() == '.icns':
            shutil.copy2(icon_src, icon_dst)
            return

        # Try to convert using sips (macOS built-in)
        if icon_src.suffix.lower() in ('.png', '.jpg', '.jpeg'):
            try:
                # Create iconset directory
                iconset_dir = resources_dir / "AppIcon.iconset"
                iconset_dir.mkdir()

                # Generate icon sizes
                sizes = [16, 32, 64, 128, 256, 512]
                for size in sizes:
                    # Regular
                    subprocess.run([
                        'sips', '-z', str(size), str(size),
                        str(icon_src), '--out',
                        str(iconset_dir / f"icon_{size}x{size}.png")
                    ], check=True, capture_output=True)

                    # @2x retina
                    size2x = size * 2
                    if size2x <= 1024:
                        subprocess.run([
                            'sips', '-z', str(size2x), str(size2x),
                            str(icon_src), '--out',
                            str(iconset_dir / f"icon_{size}x{size}@2x.png")
                        ], check=True, capture_output=True)

                # Convert iconset to icns
                subprocess.run([
                    'iconutil', '-c', 'icns', str(iconset_dir),
                    '-o', str(icon_dst)
                ], check=True, capture_output=True)

                # Clean up iconset
                shutil.rmtree(iconset_dir)
                logger.info(f"Converted icon to .icns")

            except subprocess.CalledProcessError as e:
                logger.warning(f"Icon conversion failed: {e}")
                # Fall back to just copying the original
                shutil.copy2(icon_src, resources_dir / f"AppIcon{icon_src.suffix}")

    def _copy_runtime(self, resources_dir: Path):
        """Copy the NoodleStudio runtime module."""
        runtime_dst = resources_dir / "runtime" / "noodlestudio"
        runtime_dst.mkdir(parents=True)

        # Find the runtime source
        # We need: runtime/, core/ (subset), scripting/ (subset)
        noodlestudio_src = Path(__file__).parent.parent  # noodlestudio package

        # Copy runtime module
        runtime_src = noodlestudio_src / "runtime"
        if runtime_src.exists():
            self._copy_module(runtime_src, runtime_dst / "runtime")

        # Copy core (needed for facet execution) - filter out editor code
        core_src = noodlestudio_src / "core"
        if core_src.exists():
            self._copy_module(core_src, runtime_dst / "core", is_core=True)

        # Copy scripting (for scripted facets)
        scripting_src = noodlestudio_src / "scripting"
        if scripting_src.exists():
            self._copy_module(scripting_src, runtime_dst / "scripting")

        # Copy data (for any bundled data files)
        data_src = noodlestudio_src / "data"
        if data_src.exists():
            self._copy_module(data_src, runtime_dst / "data")

        # Create __init__.py for the package
        init_content = '"""NoodleStudio runtime package (bundled)."""\n'
        (runtime_dst / "__init__.py").write_text(init_content)

        logger.info(f"Copied runtime to {runtime_dst}")

    def _copy_module(self, src: Path, dst: Path, is_core: bool = False):
        """
        Copy a Python module, excluding __pycache__ and tests.

        Args:
            src: Source directory
            dst: Destination directory
            is_core: If True, apply stricter filtering (exclude editor code)
        """
        dst.mkdir(parents=True, exist_ok=True)

        for item in src.iterdir():
            # Skip unwanted directories
            if item.name in ('__pycache__', 'tests', '.pytest_cache'):
                continue

            # Skip test files
            if item.name.startswith('test_'):
                continue

            # For core/, exclude editor-specific files
            if is_core and item.is_file():
                if self._is_editor_only_file(item.name):
                    continue

            # For core/, exclude editor-specific subdirectories
            if is_core and item.is_dir():
                if item.name in ('commands', 'neural_canvas'):
                    continue

            if item.is_dir():
                self._copy_module(item, dst / item.name, is_core=is_core)
            else:
                shutil.copy2(item, dst / item.name)

    def _is_editor_only_file(self, filename: str) -> bool:
        """Check if a file is editor-only (not needed for runtime)."""
        # Main window and mixins - editor UI
        if filename.startswith('main_window'):
            return True

        # Panel-related code
        if '_panel' in filename or '_editor' in filename:
            return True

        # Editor-specific systems
        editor_patterns = [
            'annotation_overlay',
            'computer_use_controller',
            'ghost_cursor',
            'hot_reload',
            'layout_manager',
            'noodle_code_',
            'project_manager',
            'project_migrator',
            'soft_restart',
            'theme',
            'ui_action_recorder',
            'undo_manager',
            'unity_theme',
        ]

        for pattern in editor_patterns:
            if pattern in filename:
                return True

        return False

    def _copy_project(self, resources_dir: Path):
        """Copy staged project files."""
        project_src = self.staging_dir / "project"
        project_dst = resources_dir / "project"

        if project_src.exists():
            shutil.copytree(project_src, project_dst)
            logger.info(f"Copied project to {project_dst}")
        else:
            project_dst.mkdir(parents=True)
            logger.warning("No project files to copy")


def is_macos() -> bool:
    """Check if running on macOS."""
    import platform
    return platform.system() == 'Darwin'


def get_system_python_path() -> Optional[str]:
    """Get path to system Python 3."""
    import shutil
    return shutil.which('python3')

# ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡
# જ⁀➴ ♡ Made with love. Use with love.
# Caitlyn Meeks 2026
