# ▄▄▄    ▄▄▄   ▄▄▄▄▄     ▄▄▄▄▄   ▄▄▄▄▄▄   ▄▄▄      ▄▄▄▄▄ ▄▄▄    ▄▄▄  ▄▄▄▄▄▄▄
# ████▄  ███ ▄███████▄ ▄███████▄ ███▀▀██▄ ███       ███  ████▄  ███ ███▀▀▀▀▀
# ███▀██▄███ ███   ███ ███   ███ ███  ███ ███       ███  ███▀██▄███ ███
# ███  ▀████ ███▄▄▄███ ███▄▄▄███ ███  ███ ███       ███  ███  ▀████ ███  ███▀
# ███    ███  ▀█████▀   ▀█████▀  ██████▀  ████████ ▄███▄ ███    ███ ▀██████▀
#
#   ▄▄▄▄▄▄▄   ▄▄▄▄▄   ▄▄▄▄▄▄▄    ▄▄▄▄▄▄▄
# ███▀▀▀▀▀ ▄███████▄ ███▀▀███▄ ███▀▀▀▀▀
# ███      ███   ███ ███▄▄███▀ ███▄▄
# ███      ███▄▄▄███ ███▀▀██▄  ███
# ▀███████  ▀█████▀  ███  ▀███ ▀███████
# ──────────────────────────────────────────────────────────────
#
#   MLX Code Generator - Generate Python code from NeuralGraph.
#
#   Converts visual topology to executable MLX nn.Module code.
#
# ──────────────────────────────────────────────────────────────
# MODULE:   applications.noodlestudio.core.neural_canvas.mlx_codegen
# PURPOSE:  Mlx Codegen
# LAYER:    Studio / Neural Canvas
# ──────────────────────────────────────────────────────────────
#
# KEY CLASSES:
#   MLXCodeGenerator, generate_mlx_code()
#
# ──────────────────────────────────────────────────────────────
# SPDX-License-Identifier: AGPL-3.0-or-later
# Subject to the Noodling Ethical Covenant (NEC)
# (C) 2026 Caitlyn Meeks
# Noodling Technologies, LLC
# https://noodlings.ai
# ──────────────────────────────────────────────────────────────

from typing import Dict, List, Set
from .neural_graph import NeuralGraph
from .neural_node import NeuralNode, NodeType


class MLXCodeGenerator:
    """Generate MLX Python code from NeuralGraph."""

    def __init__(self, graph: NeuralGraph):
        self.graph = graph
        self.indent_level = 0

    def generate(self) -> str:
        """
        Generate complete MLX model code.

        Returns:
            Python source code as string
        """
        code_sections = []

        # Header
        code_sections.append(self._generate_header())

        # Class definition
        code_sections.append(self._generate_class())

        # __init__ method
        code_sections.append(self._generate_init())

        # forward method
        code_sections.append(self._generate_forward())

        # Utility methods
        code_sections.append(self._generate_utility_methods())

        return '\n\n'.join(code_sections)

    def _generate_header(self) -> str:
        """Generate file header with imports."""
        return f"""# Generated by Neural Canvas
# Network: {self.graph.name}
# Date: {self.graph.modified.strftime('%Y-%m-%d %H:%M:%S') if self.graph.modified else 'N/A'}
# Parameters: {self.graph.compute_total_parameters():,}

import mlx.core as mx
import mlx.nn as nn
from typing import Dict, Any, Optional"""

    def _generate_class(self) -> str:
        """Generate class declaration and docstring."""
        class_name = self._sanitize_name(self.graph.name)
        return f'''class {class_name}(nn.Module):
    """
    {self.graph.description or self.graph.name}

    Auto-generated from Neural Canvas topology.
    """'''

    def _generate_init(self) -> str:
        """Generate __init__ method."""
        lines = ["    def __init__(self):"]
        lines.append("        super().__init__()")
        lines.append("")

        # Get nodes in topological order
        try:
            node_order = self.graph.topological_sort()
        except ValueError:
            # Graph has cycles, use any order
            node_order = list(self.graph.nodes.keys())

        # Initialize layers
        lines.append("        # Layers")
        for node_id in node_order:
            node = self.graph.nodes[node_id]
            if node.type in (NodeType.INPUT, NodeType.OUTPUT):
                continue  # Skip special nodes

            layer_code = self._generate_layer_init(node)
            if layer_code:
                lines.append(f"        {layer_code}")

        # Initialize hidden states
        lines.append("")
        lines.append("        # Hidden states")
        hidden_states = self._collect_hidden_states()
        for state_name, shape in hidden_states.items():
            shape_str = f"(1, {shape[0]})" if len(shape) == 1 else str(shape)
            lines.append(f"        self.{state_name} = mx.zeros({shape_str})")

        return '\n'.join(lines)

    def _generate_layer_init(self, node: NeuralNode) -> str:
        """Generate initialization code for a single layer."""
        layer_var = self._node_to_var(node)

        if node.type == NodeType.LSTM:
            input_dim = node.params['input_dim']
            hidden_dim = node.params['hidden_dim']
            return f"self.{layer_var} = nn.LSTM(input_size={input_dim}, hidden_size={hidden_dim})"

        elif node.type == NodeType.GRU:
            input_dim = node.params['input_dim']
            hidden_dim = node.params['hidden_dim']
            return f"self.{layer_var} = nn.GRU(input_size={input_dim}, hidden_size={hidden_dim})"

        elif node.type == NodeType.RNN:
            input_dim = node.params['input_dim']
            hidden_dim = node.params['hidden_dim']
            return f"self.{layer_var} = nn.RNN(input_size={input_dim}, hidden_size={hidden_dim})"

        elif node.type == NodeType.LINEAR:
            in_features = node.params['in_features']
            out_features = node.params['out_features']
            return f"self.{layer_var} = nn.Linear({in_features}, {out_features})"

        elif node.type == NodeType.CONV1D:
            in_ch = node.params['in_channels']
            out_ch = node.params['out_channels']
            kernel = node.params['kernel_size']
            return f"self.{layer_var} = nn.Conv1d({in_ch}, {out_ch}, kernel_size={kernel})"

        elif node.type == NodeType.DROPOUT:
            p = node.params['p']
            return f"self.{layer_var} = nn.Dropout(p={p})"

        elif node.type == NodeType.LAYER_NORM:
            shape = node.params['normalized_shape']
            shape_str = str(shape) if isinstance(shape, tuple) else f"({shape},)"
            return f"self.{layer_var} = nn.LayerNorm({shape_str})"

        elif node.type == NodeType.AFFECT_HEAD:
            state_dim = node.params['state_dim']
            hidden_dim = node.params['hidden_dim']
            affect_dim = node.params['affect_dim']
            return (f"self.{layer_var}_fc1 = nn.Linear({state_dim}, {hidden_dim})\n"
                   f"        self.{layer_var}_fc2 = nn.Linear({hidden_dim}, {affect_dim})")

        elif node.type == NodeType.QUANTUM_MICROTUBULE:
            # Import quantum microtubule layer
            input_dim = node.params['input_dim']
            hidden_dim = node.params['hidden_dim']
            return f"self.{layer_var} = QuantumMicrotubuleLayer({input_dim}, {hidden_dim})"

        # Activation functions don't need initialization
        return ""

    def _generate_forward(self) -> str:
        """Generate forward() method."""
        lines = ["    def forward(self, affect_input):"]
        lines.append('        """')
        lines.append("        Forward pass through network.")
        lines.append("")
        lines.append("        Args:")
        lines.append("            affect_input: Input affect vector (5-D)")
        lines.append("")
        lines.append("        Returns:")
        lines.append("            Dictionary with outputs")
        lines.append('        """')

        # Get execution order
        try:
            node_order = self.graph.topological_sort()
        except ValueError:
            return "        raise NotImplementedError('Graph contains cycles')"

        # Track computed values
        computed: Dict[str, str] = {}  # (node_id, port) -> variable name

        # INPUT node produces affect_input
        input_nodes = self.graph.get_input_nodes()
        if input_nodes:
            input_node = input_nodes[0]
            for port_name in input_node.outputs:
                computed[(input_node.id, port_name)] = "affect_input"

        lines.append("")
        lines.append("        # Forward pass")

        # Execute nodes in order
        for node_id in node_order:
            node = self.graph.nodes[node_id]

            if node.type == NodeType.INPUT:
                continue  # Already handled

            if node.type == NodeType.OUTPUT:
                # Build output dictionary
                lines.append("")
                lines.append("        # Collect outputs")
                lines.append("        return {")

                # Find what's connected to OUTPUT
                for conn in self.graph.get_connections_to_node(node.id):
                    output_name = conn.to_port
                    input_var = computed.get((conn.from_node, conn.from_port), "unknown")
                    lines.append(f"            '{output_name}': {input_var},")

                lines.append("        }")
                continue

            # Generate forward code for this node
            node_code = self._generate_node_forward(node, computed)
            if node_code:
                lines.append(f"        {node_code}")

        return '\n'.join(lines)

    def _generate_node_forward(self, node: NeuralNode, computed: Dict) -> str:
        """Generate forward pass code for a single node."""
        layer_var = self._node_to_var(node)

        # Collect inputs
        input_vars = {}
        for conn in self.graph.get_connections_to_node(node.id):
            input_port = conn.to_port
            input_var = computed.get((conn.from_node, conn.from_port), "unknown")
            input_vars[input_port] = input_var

        # Generate code based on node type
        if node.type == NodeType.LSTM:
            x_var = input_vars.get('x', 'unknown')
            h_var = f"self.{layer_var}_h"
            c_var = f"self.{layer_var}_c"

            code = (f"{layer_var}_out, (self.{layer_var}_h, self.{layer_var}_c) = "
                   f"self.{layer_var}({x_var}, ({h_var}, {c_var}))")

            # Mark outputs as computed
            computed[(node.id, 'h_out')] = f"{layer_var}_out"
            computed[(node.id, 'c_out')] = f"self.{layer_var}_c"

            return code

        elif node.type == NodeType.GRU:
            x_var = input_vars.get('x', 'unknown')
            h_var = f"self.{layer_var}_h"

            code = (f"{layer_var}_out, self.{layer_var}_h = "
                   f"self.{layer_var}({x_var}, {h_var})")

            computed[(node.id, 'h_out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.LINEAR:
            x_var = input_vars.get('x', 'unknown')
            code = f"{layer_var}_out = self.{layer_var}({x_var})"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.TANH:
            x_var = input_vars.get('x', 'unknown')
            code = f"{layer_var}_out = mx.tanh({x_var})"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.RELU:
            x_var = input_vars.get('x', 'unknown')
            code = f"{layer_var}_out = mx.maximum({x_var}, 0)"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.SIGMOID:
            x_var = input_vars.get('x', 'unknown')
            code = f"{layer_var}_out = mx.sigmoid({x_var})"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.DROPOUT:
            x_var = input_vars.get('x', 'unknown')
            code = f"{layer_var}_out = self.{layer_var}({x_var})"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.STATE_CONCAT:
            # Concatenate inputs
            input_names = ['fast', 'medium', 'slow']
            concat_vars = [input_vars.get(name, f"unknown_{name}") for name in input_names]
            code = f"{layer_var}_out = mx.concatenate([{', '.join(concat_vars)}], axis=-1)"
            computed[(node.id, 'state')] = f"{layer_var}_out"
            return code

        elif node.type == NodeType.AFFECT_HEAD:
            state_var = input_vars.get('state', 'unknown')
            code_lines = [
                f"{layer_var}_hidden = mx.tanh(self.{layer_var}_fc1({state_var}))",
                f"{layer_var}_affect = self.{layer_var}_fc2({layer_var}_hidden)"
            ]

            # Split into individual affect dimensions
            for i, dim_name in enumerate(['valence', 'arousal', 'fear', 'sorrow', 'boredom']):
                computed[(node.id, dim_name)] = f"{layer_var}_affect[0, {i}]"

            return '\n        '.join(code_lines)

        # Default: pass through
        if input_vars:
            first_input = next(iter(input_vars.values()))
            code = f"{layer_var}_out = {first_input}  # Passthrough"
            computed[(node.id, 'out')] = f"{layer_var}_out"
            return code

        return f"# TODO: Implement {node.type.value}"

    def _generate_utility_methods(self) -> str:
        """Generate utility methods (load_weights, reset_state, etc.)."""
        lines = []

        # load_weights method
        lines.append("    def load_weights(self, checkpoint_path: str):")
        lines.append('        """Load weights from .npz checkpoint."""')
        lines.append("        weights = mx.load(checkpoint_path)")
        lines.append("        self.load_weights_dict(weights)")
        lines.append("")

        # reset_state method
        lines.append("    def reset_state(self):")
        lines.append('        """Reset hidden states."""')
        hidden_states = self._collect_hidden_states()
        for state_name, shape in hidden_states.items():
            shape_str = f"(1, {shape[0]})" if len(shape) == 1 else str(shape)
            lines.append(f"        self.{state_name} = mx.zeros({shape_str})")

        return '\n'.join(lines)

    def _collect_hidden_states(self) -> Dict[str, tuple]:
        """Collect all hidden states needed (LSTM h/c, GRU h, etc.)."""
        states = {}

        for node in self.graph.nodes.values():
            layer_var = self._node_to_var(node)

            if node.type == NodeType.LSTM:
                hidden_dim = node.params['hidden_dim']
                states[f"{layer_var}_h"] = (hidden_dim,)
                states[f"{layer_var}_c"] = (hidden_dim,)

            elif node.type == NodeType.GRU:
                hidden_dim = node.params['hidden_dim']
                states[f"{layer_var}_h"] = (hidden_dim,)

            elif node.type == NodeType.RNN:
                hidden_dim = node.params['hidden_dim']
                states[f"{layer_var}_h"] = (hidden_dim,)

        return states

    def _node_to_var(self, node: NeuralNode) -> str:
        """Convert node to variable name."""
        # Use node name, sanitized
        var_name = self._sanitize_name(node.name)
        return var_name.lower().replace(' ', '_')

    def _sanitize_name(self, name: str) -> str:
        """Sanitize name for use as Python identifier."""
        # Remove special characters, replace spaces with underscores
        sanitized = ''.join(c if c.isalnum() or c == '_' else '_' for c in name)

        # Ensure doesn't start with digit
        if sanitized and sanitized[0].isdigit():
            sanitized = 'n_' + sanitized

        # Capitalize for class names
        if name and name[0].isupper():
            sanitized = sanitized.title().replace('_', '')

        return sanitized or 'UnknownNode'


def generate_mlx_code(graph: NeuralGraph) -> str:
    """
    Convenience function to generate MLX code from graph.

    Args:
        graph: NeuralGraph to convert

    Returns:
        Python source code string
    """
    generator = MLXCodeGenerator(graph)
    return generator.generate()

# ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡
# જ⁀➴ ♡ Made with love. Use with love.
# Caitlyn Meeks 2026
