# ▄▄▄    ▄▄▄   ▄▄▄▄▄     ▄▄▄▄▄   ▄▄▄▄▄▄   ▄▄▄      ▄▄▄▄▄ ▄▄▄    ▄▄▄  ▄▄▄▄▄▄▄
# ████▄  ███ ▄███████▄ ▄███████▄ ███▀▀██▄ ███       ███  ████▄  ███ ███▀▀▀▀▀
# ███▀██▄███ ███   ███ ███   ███ ███  ███ ███       ███  ███▀██▄███ ███
# ███  ▀████ ███▄▄▄███ ███▄▄▄███ ███  ███ ███       ███  ███  ▀████ ███  ███▀
# ███    ███  ▀█████▀   ▀█████▀  ██████▀  ████████ ▄███▄ ███    ███ ▀██████▀
#
#  ▄▄▄▄▄▄▄   ▄▄▄▄▄   ▄▄▄▄▄▄▄    ▄▄▄▄▄▄▄
# ███▀▀▀▀▀ ▄███████▄ ███▀▀███▄ ███▀▀▀▀▀
# ███      ███   ███ ███▄▄███▀ ███▄▄
# ███      ███▄▄▄███ ███▀▀██▄  ███
# ▀███████  ▀█████▀  ███  ▀███ ▀███████
# ──────────────────────────────────────────────────────────────
#
#   Generated Charm Network (Auto-Generated)
#
#   This file was automatically created by Neural Canvas when
#   you clicked "Export to MLX". It's a runnable neural network
#   in Apple's MLX framework.
#
#   Think of this as the "compiled" version of your visual node
#   graph. When you draw boxes and connect them in Neural Canvas,
#   this file is what actually runs on your hardware.
#
#   The network here processes affect (emotions) at three speeds:
#   - Fast: moment-to-moment feelings (seconds)
#   - Medium: mood changes (minutes)
#   - Slow: long-term emotional patterns (hours/days)
#
#   NOTE: This file is auto-generated. Edit the Neural Canvas
#   graph and re-export if you need changes.
#
# ──────────────────────────────────────────────────────────────
# MODULE:   applications.noodlestudio.generated_charm_network
# PURPOSE:  Auto-generated MLX neural network from Neural Canvas
# LAYER:    Generated / Neural Network
# ──────────────────────────────────────────────────────────────
#
# Generated by Neural Canvas
# Network: CharmNetwork Default
# Date: 2025-12-08 19:00:00
# Parameters: 5,749
#
# ──────────────────────────────────────────────────────────────
# SPDX-License-Identifier: AGPL-3.0-or-later
# Subject to the Noodling Ethical Covenant (NEC)
# (C) 2026 Caitlyn Meeks
# Noodling Technologies, LLC
# https://noodlings.ai
# ──────────────────────────────────────────────────────────────

import mlx.core as mx
import mlx.nn as nn
from typing import Dict, Any, Optional

class CharmnetworkDefault(nn.Module):
    """
    Hierarchical temporal affect processor: Fast LSTM (seconds) + Medium LSTM (minutes) + Slow GRU (hours/days)

    Auto-generated from Neural Canvas topology.
    """

    def __init__(self):
        super().__init__()

        # Layers
        self.fastlstm = nn.LSTM(input_size=5, hidden_size=16)
        self.mediumlstm = nn.LSTM(input_size=16, hidden_size=16)
        self.slowgru = nn.GRU(input_size=16, hidden_size=8)
        self.affectpredictor_fc1 = nn.Linear(40, 32)
        self.affectpredictor_fc2 = nn.Linear(32, 5)

        # Hidden states
        self.fastlstm_h = mx.zeros((1, 16))
        self.fastlstm_c = mx.zeros((1, 16))
        self.mediumlstm_h = mx.zeros((1, 16))
        self.mediumlstm_c = mx.zeros((1, 16))
        self.slowgru_h = mx.zeros((1, 8))

    def forward(self, affect_input):
        """
        Forward pass through network.

        Args:
            affect_input: Input affect vector (5-D)

        Returns:
            Dictionary with outputs
        """

        # Forward pass
        fastlstm_out, (self.fastlstm_h, self.fastlstm_c) = self.fastlstm(affect_input, (self.fastlstm_h, self.fastlstm_c))
        mediumlstm_out, (self.mediumlstm_h, self.mediumlstm_c) = self.mediumlstm(fastlstm_out, (self.mediumlstm_h, self.mediumlstm_c))
        slowgru_out, self.slowgru_h = self.slowgru(mediumlstm_out, self.slowgru_h)
        phenomenalstate_out = mx.concatenate([fastlstm_out, mediumlstm_out, slowgru_out], axis=-1)
        affectpredictor_hidden = mx.tanh(self.affectpredictor_fc1(phenomenalstate_out))
        affectpredictor_affect = self.affectpredictor_fc2(affectpredictor_hidden)

        # Collect outputs
        return {
            'state': phenomenalstate_out,
        }

    def load_weights(self, checkpoint_path: str):
        """Load weights from .npz checkpoint."""
        weights = mx.load(checkpoint_path)
        self.load_weights_dict(weights)

    def reset_state(self):
        """Reset hidden states."""
        self.fastlstm_h = mx.zeros((1, 16))
        self.fastlstm_c = mx.zeros((1, 16))
        self.mediumlstm_h = mx.zeros((1, 16))
        self.mediumlstm_c = mx.zeros((1, 16))
        self.slowgru_h = mx.zeros((1, 8))

# ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡ ～ ♡
# જ⁀➴ ♡ Made with love. Use with love.
# Caitlyn Meeks 2026
